version: '3'
services:
  consul-server:
    image: hashicorp/consul:latest
    restart: always
    networks:
      - app-net
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -node=consul-server -server -ui -bootstrap -bootstrap-expect=1 -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      resources:
        limits:
          memory: 512M

  gateway-service:
    image: olexienkovova/gateway-service:1.0
    restart: always
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Djwt.secret.key=secret
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    ports:
      - "8080:8080"
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - consul-server

  user-service:
    image: olexienkovova/user-service:1.0
    restart: always
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Dspring.data.mongodb.uri=mongodb+srv://root:Zhtkgs5HIpPsaEuX@note.hvyhamq.mongodb.net/note?retryWrites=true&w=majority
        -Dauthorization.cookie.validity=2505600
        -Djwt.secret.key=secret
        -Djwt.token.validity=2592000000
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - consul-server

  notes-service:
    image: olexienkovova/notes-service:1.0
    restart: always
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Dspring.data.mongodb.uri=mongodb+srv://root:Zhtkgs5HIpPsaEuX@note.hvyhamq.mongodb.net/note?retryWrites=true&w=majority
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - consul-server

  invitation-service:
    image: olexienkovova/invitation-service:1.0
    restart: always
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Dspring.data.mongodb.uri=mongodb+srv://root:Zhtkgs5HIpPsaEuX@note.hvyhamq.mongodb.net/note?retryWrites=true&w=majority
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - consul-server

networks:
  app-net:
    driver: overlay