version: '3'
services:
  service-discovery-server-1:
    image: olexienkovova/service-discovery-server:1.0
    environment:
      - JAVA_OPTS=
        -Deureka.instance.hostname=service-discovery-server-12
        -Deureka.client.service-url.defaultZone=http://service-discovery-server-1:8080/eureka,http://service-discovery-server-2:8080/eureka,http://service-discovery-server-3:8080/eureka
    ports:
      - "9001:8080"
    networks:
      - app-net
    mem_limit: 512m
  service-discovery-server-2:
    image: olexienkovova/service-discovery-server:1.0
    environment:
      - JAVA_OPTS=
        -Deureka.instance.hostname=service-discovery-server-2
        -Deureka.client.service-url.defaultZone=http://service-discovery-server-1:8080/eureka,http://service-discovery-server-2:8080/eureka,http://service-discovery-server-3:8080/eureka
    ports:
      - "9002:8080"
    networks:
      - app-net
    mem_limit: 512m
  service-discovery-server-3:
    image: olexienkovova/service-discovery-server:1.0
    environment:
      - JAVA_OPTS=
        -Deureka.instance.hostname=service-discovery-server-3
        -Deureka.client.service-url.defaultZone=http://service-discovery-server-1:8080/eureka,http://service-discovery-server-2:8080/eureka,http://service-discovery-server-3:8080/eureka
    ports:
      - "9003:8080"
    networks:
      - app-net
    mem_limit: 512m
  gateway-service:
    image: olexienkovova/gateway-service:1.0
    environment:
      - JAVA_OPTS=
        -Deureka.client.service-url.defaultZone=http://service-discovery-server-1:8080/eureka,http://service-discovery-server-2:8080/eureka,http://service-discovery-server-3:8080/eureka
        -Djwt.secret.key=secret
    depends_on:
      - service-discovery-server-1
      - service-discovery-server-2
      - service-discovery-server-3
    ports:
      - "9000:8080"
    networks:
      - app-net
    mem_limit: 512m
  user-service:
    image: olexienkovova/user-service:1.0
    environment:
      - JAVA_OPTS=
        -Deureka.client.service-url.defaultZone=http://service-discovery-server-1:8080/eureka,http://service-discovery-server-2:8080/eureka,http://service-discovery-server-3:8080/eureka
        -Dspring.datasource.url=jdbc:mysql://user-service-db:3306/user?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC
        -Dauthorization.cookie.validity=2505600
        -Dspring.datasource.password=GdU_oPhgl4G6d
        -Dspring.datasource.username=root
        -Djwt.secret.key=secret
        -Djwt.token.validity=2592000000
    depends_on:
      - service-discovery-server-1
      - service-discovery-server-2
      - service-discovery-server-3
      - user-service-db
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - "8080"
    networks:
      - app-net
    mem_limit: 512m
  notes-service:
    image: olexienkovova/notes-service:1.0
    environment:
      - JAVA_OPTS=
        -Deureka.client.service-url.defaultZone=http://service-discovery-server-1:8080/eureka,http://service-discovery-server-2:8080/eureka,http://service-discovery-server-3:8080/eureka
        -Dspring.datasource.url=jdbc:mysql://notes-service-db:3306/notes?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC
        -Dspring.datasource.password=GdU_oPhgl4G6d
        -Dspring.datasource.username=root
    depends_on:
      - service-discovery-server-1
      - service-discovery-server-2
      - service-discovery-server-3
      - notes-service-db
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - "8080"
    networks:
      - app-net
    mem_limit: 512m
  invitation-service:
    image: olexienkovova/invitation-service:1.0
    environment:
      - JAVA_OPTS=
        -Deureka.client.service-url.defaultZone=http://service-discovery-server-1:8080/eureka,http://service-discovery-server-2:8080/eureka,http://service-discovery-server-3:8080/eureka
        -Dspring.datasource.url=jdbc:mysql://invitation-service-db:3306/invitation?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC
        -Dspring.datasource.password=GdU_oPhgl4G6d
        -Dspring.datasource.username=root
    depends_on:
      - service-discovery-server-1
      - service-discovery-server-2
      - service-discovery-server-3
      - invitation-service-db
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - "8080"
    networks:
      - app-net
    mem_limit: 512m
  user-service-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=GdU_oPhgl4G6d
    expose:
      - "3306"
    networks:
      - app-net
    mem_limit: 512m
  notes-service-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=GdU_oPhgl4G6d
    expose:
      - "3306"
    networks:
      - app-net
    mem_limit: 512m
  invitation-service-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=GdU_oPhgl4G6d
    expose:
      - "3306"
    networks:
      - app-net
    mem_limit: 512m

networks:
  app-net:
    driver: bridge