version: '3'
services:
  consul-server:
    image: hashicorp/consul:latest
    networks:
      - app-net
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -node=consul-server -server -ui -bootstrap -bootstrap-expect=1 -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"
    deploy:
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M

  gateway-service:
    image: olexienkovova/gateway-service:1.0
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Djwt.secret.key=secret
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    ports:
      - "8080:8080"
    networks:
      - app-net
    depends_on:
      - consul-server
    deploy:
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: curl -sS http://gateway-service:8080/actuator/health || echo 1
      interval: 30s
      timeout: 3s
      retries: 12

  user-service:
    image: olexienkovova/user-service:1.0
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Dspring.data.mongodb.uri=mongodb+srv://root:Zhtkgs5HIpPsaEuX@note.hvyhamq.mongodb.net/note?retryWrites=true&w=majority
        -Dauthorization.cookie.validity=2505600
        -Djwt.secret.key=secret
        -Djwt.token.validity=2592000000
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    networks:
      - app-net
    depends_on:
      - consul-server
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: curl -sS http://user-service:8080/actuator/health || echo 1
      interval: 30s
      timeout: 3s
      retries: 12

  notes-service:
    image: olexienkovova/notes-service:1.0
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Dspring.data.mongodb.uri=mongodb+srv://root:Zhtkgs5HIpPsaEuX@note.hvyhamq.mongodb.net/note?retryWrites=true&w=majority
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    networks:
      - app-net
    depends_on:
      - consul-server
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: curl -sS http://notes-service:8080/actuator/health || echo 1
      interval: 30s
      timeout: 3s
      retries: 12

  invitation-service:
    image: olexienkovova/invitation-service:1.0
    environment:
      - JAVA_OPTS=
        -Dspring.cloud.consul.host=consul-server
        -Dspring.data.mongodb.uri=mongodb+srv://root:Zhtkgs5HIpPsaEuX@note.hvyhamq.mongodb.net/note?retryWrites=true&w=majority
        -Dspring.cloud.consul.discovery.instanceZone=zone1
    networks:
      - app-net
    depends_on:
      - consul-server
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: curl -sS http://invitation-service:8080/actuator/health || echo 1
      interval: 30s
      timeout: 3s
      retries: 12

networks:
  app-net:
    driver: bridge